// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WXZ8SX_HFT_2021221.Data;

namespace WXZ8SX_HFT_2021221.Data.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20211016125915_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WXZ8SX_HFT_2021221.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfSongs")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            AlbumName = "D'eux",
                            ArtistId = 1,
                            GenreId = 1,
                            Length = 47.159999999999997,
                            NumberOfSongs = 12,
                            Rating = 4.7000000000000002,
                            ReleasedDate = new DateTime(1995, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AlbumId = 2,
                            AlbumName = "A New Day Has Come",
                            ArtistId = 1,
                            GenreId = 1,
                            Length = 72.140000000000001,
                            NumberOfSongs = 17,
                            Rating = 4.7000000000000002,
                            ReleasedDate = new DateTime(2002, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AlbumId = 3,
                            AlbumName = "Dangerous",
                            ArtistId = 2,
                            GenreId = 11,
                            Length = 77.030000000000001,
                            NumberOfSongs = 14,
                            Rating = 4.7999999999999998,
                            ReleasedDate = new DateTime(1991, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AlbumId = 4,
                            AlbumName = "Bad",
                            ArtistId = 2,
                            GenreId = 11,
                            Length = 48.399999999999999,
                            NumberOfSongs = 11,
                            Rating = 4.7999999999999998,
                            ReleasedDate = new DateTime(1987, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AlbumId = 5,
                            AlbumName = "Catch a Fire",
                            ArtistId = 3,
                            GenreId = 12,
                            Length = 37.509999999999998,
                            NumberOfSongs = 11,
                            Rating = 4.7999999999999998,
                            ReleasedDate = new DateTime(1973, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AlbumId = 6,
                            AlbumName = "Queen",
                            ArtistId = 4,
                            GenreId = 8,
                            Length = 66.189999999999998,
                            NumberOfSongs = 19,
                            Rating = 4.7000000000000002,
                            ReleasedDate = new DateTime(2018, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AlbumId = 7,
                            AlbumName = "Future Nostalgia",
                            ArtistId = 5,
                            GenreId = 1,
                            Length = 37.170000000000002,
                            NumberOfSongs = 11,
                            Rating = 4.7999999999999998,
                            ReleasedDate = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AlbumId = 8,
                            AlbumName = "In My Memory",
                            ArtistId = 6,
                            GenreId = 6,
                            Length = 68.189999999999998,
                            NumberOfSongs = 9,
                            Rating = 4.7000000000000002,
                            ReleasedDate = new DateTime(2001, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WXZ8SX_HFT_2021221.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfAlbums")
                        .HasColumnType("int");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            ArtistName = "Celine Dion",
                            DateOfBirth = new DateTime(1968, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfAlbums = 27
                        },
                        new
                        {
                            ArtistId = 2,
                            ArtistName = "Michael Jackson",
                            DateOfBirth = new DateTime(1958, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfAlbums = 10
                        },
                        new
                        {
                            ArtistId = 3,
                            ArtistName = "Bob Marley",
                            DateOfBirth = new DateTime(1945, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfAlbums = 13
                        },
                        new
                        {
                            ArtistId = 4,
                            ArtistName = "Nicki Minaj",
                            DateOfBirth = new DateTime(1982, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfAlbums = 4
                        },
                        new
                        {
                            ArtistId = 5,
                            ArtistName = "Dua Lipa",
                            DateOfBirth = new DateTime(1995, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfAlbums = 2
                        },
                        new
                        {
                            ArtistId = 6,
                            ArtistName = "Tiesto",
                            DateOfBirth = new DateTime(1969, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfAlbums = 6
                        });
                });

            modelBuilder.Entity("WXZ8SX_HFT_2021221.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Pop"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Metal"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Rock"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Flamenco"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Jazz"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "House"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Hip Hop"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "Rap"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "Folk"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Latin"
                        },
                        new
                        {
                            GenreId = 11,
                            GenreName = "R&B and soul"
                        },
                        new
                        {
                            GenreId = 12,
                            GenreName = "Reggae"
                        });
                });

            modelBuilder.Entity("WXZ8SX_HFT_2021221.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Singer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("SongId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            AlbumId = 1,
                            Length = 4.1399999999999997,
                            Name = "Pour que tu m'aime encore",
                            Singer = "Celine Dion",
                            Writer = "Jean-Jacques Goldman"
                        },
                        new
                        {
                            SongId = 2,
                            AlbumId = 1,
                            Length = 4.2300000000000004,
                            Name = "Le Ballet",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 3,
                            AlbumId = 1,
                            Length = 3.5699999999999998,
                            Name = "Regarde-moi",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 4,
                            AlbumId = 1,
                            Length = 4.3300000000000001,
                            Name = "Je sais pas",
                            Singer = "Celine Dion",
                            Writer = "Goldman, JKapler"
                        },
                        new
                        {
                            SongId = 5,
                            AlbumId = 1,
                            Length = 3.5,
                            Name = "La memoire d'Abraham",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 6,
                            AlbumId = 1,
                            Length = 3.2400000000000002,
                            Name = "Cherche encore",
                            Singer = "Celine Dion",
                            Writer = "Erick Benzi"
                        },
                        new
                        {
                            SongId = 7,
                            AlbumId = 1,
                            Length = 4.1500000000000004,
                            Name = "Destin",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 8,
                            AlbumId = 1,
                            Length = 3.3300000000000001,
                            Name = "Les derniers seront les premiers",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 9,
                            AlbumId = 1,
                            Length = 3.2599999999999998,
                            Name = "J'irai ou tu iras",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 10,
                            AlbumId = 1,
                            Length = 4.2400000000000002,
                            Name = "J'attendais",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 11,
                            AlbumId = 1,
                            Length = 4.0999999999999996,
                            Name = "Priere paienne",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 12,
                            AlbumId = 1,
                            Length = 2.5699999999999998,
                            Name = "Vole",
                            Singer = "Celine Dion",
                            Writer = "Goldman"
                        },
                        new
                        {
                            SongId = 13,
                            AlbumId = 2,
                            Length = 3.2999999999999998,
                            Name = "I'm Alive",
                            Singer = "Celine Dion",
                            Writer = "Kristian Lundin, Andreas Carlsson"
                        },
                        new
                        {
                            SongId = 14,
                            AlbumId = 2,
                            Length = 4.1299999999999999,
                            Name = "Right in Front of You",
                            Singer = "Celine Dion",
                            Writer = "Steve Morales, Sheppard Solomon, Kara DioGuardi"
                        },
                        new
                        {
                            SongId = 15,
                            AlbumId = 2,
                            Length = 4.0800000000000001,
                            Name = "Have You Ever Been in Love",
                            Singer = "Celine Dion",
                            Writer = "Anders Bagge, Peer Åström, Tom Nichols, Daryl Hall, Laila Bagge"
                        },
                        new
                        {
                            SongId = 16,
                            AlbumId = 2,
                            Length = 3.25,
                            Name = "Rain, Tax (It's Inevitable)",
                            Singer = "Celine Dion",
                            Writer = "Terry Britten, Charlie Dore"
                        },
                        new
                        {
                            SongId = 17,
                            AlbumId = 2,
                            Length = 4.2300000000000004,
                            Name = "A New Day Has Come",
                            Singer = "Celine Dion",
                            Writer = "Aldo Nova, Stephan Moccio"
                        },
                        new
                        {
                            SongId = 18,
                            AlbumId = 2,
                            Length = 3.3700000000000001,
                            Name = "Ten Days",
                            Singer = "Celine Dion",
                            Writer = "Nova, Maxime Le Forestier, Gérald de Palmas"
                        },
                        new
                        {
                            SongId = 19,
                            AlbumId = 2,
                            Length = 5.1900000000000004,
                            Name = "Goodbye's (The Saddest Word)",
                            Singer = "Celine Dion",
                            Writer = "Robert John Mutt Lange"
                        },
                        new
                        {
                            SongId = 20,
                            AlbumId = 2,
                            Length = 5.3399999999999999,
                            Name = "Prayer",
                            Singer = "Celine Dion",
                            Writer = "Corey Hart"
                        },
                        new
                        {
                            SongId = 21,
                            AlbumId = 2,
                            Length = 4.4699999999999998,
                            Name = "I Surrender",
                            Singer = "Celine Dion",
                            Writer = "Louis Biancaniello, Sam Watters"
                        },
                        new
                        {
                            SongId = 22,
                            AlbumId = 2,
                            Length = 4.1699999999999999,
                            Name = "At Last",
                            Singer = "Celine Dion",
                            Writer = "Mack Gordon, Harry Warren"
                        },
                        new
                        {
                            SongId = 23,
                            AlbumId = 2,
                            Length = 4.1600000000000001,
                            Name = "Super Love",
                            Singer = "Celine Dion",
                            Writer = "Roche, Shelly Peiken"
                        },
                        new
                        {
                            SongId = 24,
                            AlbumId = 2,
                            Length = 4.0999999999999996,
                            Name = "Sorry for Love",
                            Singer = "Celine Dion",
                            Writer = "DioGuardi, Bagge, Åström, Arnthor Birgisson"
                        },
                        new
                        {
                            SongId = 25,
                            AlbumId = 2,
                            Length = 3.52,
                            Name = "Aun Existe Amor",
                            Singer = "Celine Dion",
                            Writer = "Riccardo Cocciante, Ignacio Ballesteros-Diaz"
                        },
                        new
                        {
                            SongId = 26,
                            AlbumId = 2,
                            Length = 3.2799999999999998,
                            Name = "The Greatest Reward",
                            Singer = "Celine Dion",
                            Writer = "Pascal Obispo, Carlsson, Jörgen Elofsson, Lionel Florence, Patrice Guirao"
                        },
                        new
                        {
                            SongId = 27,
                            AlbumId = 2,
                            Length = 3.48,
                            Name = "When the Wrong One Loves You Right",
                            Singer = "Celine Dion",
                            Writer = "Martin Briley, Francis Galluccio, Marjorie Maye"
                        },
                        new
                        {
                            SongId = 28,
                            AlbumId = 2,
                            Length = 5.4199999999999999,
                            Name = "A New Day Has Come",
                            Singer = "Celine Dion",
                            Writer = "Nova, Moccio"
                        },
                        new
                        {
                            SongId = 29,
                            AlbumId = 2,
                            Length = 2.5699999999999998,
                            Name = "Nature Boy",
                            Singer = "Celine Dion",
                            Writer = "eden ahbez"
                        },
                        new
                        {
                            SongId = 30,
                            AlbumId = 3,
                            Length = 5.3899999999999997,
                            Name = "Jam",
                            Singer = "Michael Jackson",
                            Writer = "Michael Jackson, René Moore, Bruce Swedien, Teddy Riley"
                        },
                        new
                        {
                            SongId = 31,
                            AlbumId = 3,
                            Length = 5.2400000000000002,
                            Name = "Why You Wanna Trip on Me",
                            Singer = "Michael Jackson",
                            Writer = "RileyBernard Belle"
                        },
                        new
                        {
                            SongId = 32,
                            AlbumId = 3,
                            Length = 6.3200000000000003,
                            Name = "In the Closet",
                            Singer = "Michael Jackson",
                            Writer = "Jackson, Riley"
                        },
                        new
                        {
                            SongId = 33,
                            AlbumId = 3,
                            Length = 3.4199999999999999,
                            Name = "She Drives Me Wild",
                            Singer = "Michael Jackson",
                            Writer = "Jackson, Riley, Aqil Davidson"
                        },
                        new
                        {
                            SongId = 34,
                            AlbumId = 3,
                            Length = 4.5899999999999999,
                            Name = "Can't Let Her Get Away",
                            Singer = "Michael Jackson",
                            Writer = "Jackson, Riley"
                        },
                        new
                        {
                            SongId = 35,
                            AlbumId = 3,
                            Length = 6.25,
                            Name = "Heal the World",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 36,
                            AlbumId = 3,
                            Length = 4.1600000000000001,
                            Name = "Black or White",
                            Singer = "Michael Jackson",
                            Writer = "Jackson, Bill Bottrell"
                        },
                        new
                        {
                            SongId = 37,
                            AlbumId = 3,
                            Length = 6.3499999999999996,
                            Name = "Who Is It",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 38,
                            AlbumId = 3,
                            Length = 5.2999999999999998,
                            Name = "Give In to Me",
                            Singer = "Michael Jackson",
                            Writer = "Jackson, Bottrell"
                        },
                        new
                        {
                            SongId = 39,
                            AlbumId = 3,
                            Length = 7.4100000000000001,
                            Name = "Will You Be There",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 40,
                            AlbumId = 3,
                            Length = 5.5700000000000003,
                            Name = "Keep the Faith",
                            Singer = "Michael Jackson",
                            Writer = "Jackson, Glen Ballard, Siedah Garrett"
                        },
                        new
                        {
                            SongId = 41,
                            AlbumId = 3,
                            Length = 3.2200000000000002,
                            Name = "Gone Too Soon",
                            Singer = "Michael Jackson",
                            Writer = "Larry Grossman, Buz Kohan"
                        },
                        new
                        {
                            SongId = 42,
                            AlbumId = 3,
                            Length = 6.5700000000000003,
                            Name = "Dangerous",
                            Singer = "Michael Jackson",
                            Writer = "Jackson, Bottrell, Riley"
                        },
                        new
                        {
                            SongId = 43,
                            AlbumId = 4,
                            Length = 4.0800000000000001,
                            Name = "Bad",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 44,
                            AlbumId = 4,
                            Length = 4.5899999999999999,
                            Name = "The Way You Make Me Feel",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 45,
                            AlbumId = 4,
                            Length = 4.0300000000000002,
                            Name = "Speed Demon",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 46,
                            AlbumId = 4,
                            Length = 3.5499999999999998,
                            Name = "Liberian Girl",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 47,
                            AlbumId = 4,
                            Length = 4.0899999999999999,
                            Name = "Just Good Friends",
                            Singer = "Michael Jackson",
                            Writer = "Terry Britten, Graham Lyle"
                        },
                        new
                        {
                            SongId = 48,
                            AlbumId = 4,
                            Length = 3.5499999999999998,
                            Name = "Another Part of Me",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 49,
                            AlbumId = 4,
                            Length = 5.21,
                            Name = "Man in the Mirror",
                            Singer = "Michael Jackson",
                            Writer = "Siedah Garrett, Glen Ballard"
                        },
                        new
                        {
                            SongId = 50,
                            AlbumId = 4,
                            Length = 4.2699999999999996,
                            Name = "I Just Can't Stop Loving You",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 51,
                            AlbumId = 4,
                            Length = 4.4199999999999999,
                            Name = "Dirty Diana",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 52,
                            AlbumId = 4,
                            Length = 4.2000000000000002,
                            Name = "Smooth Criminal",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 53,
                            AlbumId = 4,
                            Length = 4.4100000000000001,
                            Name = "Leave Me Alone",
                            Singer = "Michael Jackson",
                            Writer = "Jackson"
                        },
                        new
                        {
                            SongId = 54,
                            AlbumId = 5,
                            Length = 4.1100000000000003,
                            Name = "Concrete Jungle",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 55,
                            AlbumId = 5,
                            Length = 3.3700000000000001,
                            Name = "Stir It Up",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 56,
                            AlbumId = 5,
                            Length = 4.4000000000000004,
                            Name = "High Tide or Low Tide",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 57,
                            AlbumId = 5,
                            Length = 3.52,
                            Name = "Stop That Train",
                            Singer = "Bob Marley",
                            Writer = "Tosh"
                        },
                        new
                        {
                            SongId = 58,
                            AlbumId = 5,
                            Length = 2.5699999999999998,
                            Name = "400 Years",
                            Singer = "Bob Marley",
                            Writer = "Tosh"
                        },
                        new
                        {
                            SongId = 59,
                            AlbumId = 5,
                            Length = 4.0,
                            Name = "Baby We've Got a Date (Rock It Baby)",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 60,
                            AlbumId = 5,
                            Length = 5.0499999999999998,
                            Name = "Midnight Ravers",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 61,
                            AlbumId = 5,
                            Length = 3.2599999999999998,
                            Name = "All Day All Night",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 62,
                            AlbumId = 5,
                            Length = 2.52,
                            Name = "Slave Driver",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 63,
                            AlbumId = 5,
                            Length = 3.3999999999999999,
                            Name = "Kinky Reggae",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 64,
                            AlbumId = 5,
                            Length = 5.1299999999999999,
                            Name = "No More Trouble",
                            Singer = "Bob Marley",
                            Writer = "Bob Marley"
                        },
                        new
                        {
                            SongId = 65,
                            AlbumId = 6,
                            Length = 4.54,
                            Name = "Ganja Burn",
                            Singer = "Nicki Minaj",
                            Writer = "Onika Maraj, Jeremy Reid, Jairus Mozee"
                        },
                        new
                        {
                            SongId = 66,
                            AlbumId = 6,
                            Length = 4.5499999999999998,
                            Name = "Majesty",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Timothy McKenzie, Marshall Mathers, Luis Resto"
                        },
                        new
                        {
                            SongId = 67,
                            AlbumId = 6,
                            Length = 4.3899999999999997,
                            Name = "Barbie Dreams",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Rashad Smith, Melvin Hough II, Rivelino Raoul Wouter, Christopher Wallace, James Brown, Fred Wesley"
                        },
                        new
                        {
                            SongId = 68,
                            AlbumId = 6,
                            Length = 3.1200000000000001,
                            Name = "Rich Sex",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Dwayne Carter, Reid, Jawara Headley, Aubry Delaine"
                        },
                        new
                        {
                            SongId = 69,
                            AlbumId = 6,
                            Length = 3.1299999999999999,
                            Name = "Hard White",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Matthew Samuels, Ramon Ibanga Jr., Brittany Hazzard"
                        },
                        new
                        {
                            SongId = 70,
                            AlbumId = 6,
                            Length = 3.0899999999999999,
                            Name = "Bed",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Benjamin Diehl, Gamal Lewis, Brett Bailey, Mescon David Asher, Dwayne Chin-Quee"
                        },
                        new
                        {
                            SongId = 71,
                            AlbumId = 6,
                            Length = 3.1800000000000002,
                            Name = "Thought I Knew You",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Abel Tesfaye, Hazzard, Reid"
                        },
                        new
                        {
                            SongId = 72,
                            AlbumId = 6,
                            Length = 2.3399999999999999,
                            Name = "Run & Hide",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Hazzard, Rupert Thomas Jr., Masamune Kudo"
                        },
                        new
                        {
                            SongId = 73,
                            AlbumId = 6,
                            Length = 6.0999999999999996,
                            Name = "Chun Swae",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Khalif Brown, Leland Wayne"
                        },
                        new
                        {
                            SongId = 74,
                            AlbumId = 6,
                            Length = 3.1099999999999999,
                            Name = "Chun-Li",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Reid"
                        },
                        new
                        {
                            SongId = 75,
                            AlbumId = 6,
                            Length = 3.4100000000000001,
                            Name = "LLC",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Rasool Diaz, Wesley Dees, Jason Fox"
                        },
                        new
                        {
                            SongId = 76,
                            AlbumId = 6,
                            Length = 3.1899999999999999,
                            Name = "Good Form",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Michael Williams II, Asheton Hogan"
                        },
                        new
                        {
                            SongId = 77,
                            AlbumId = 6,
                            Length = 3.27,
                            Name = "Nip Tuck",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Hazzard, Jeremy Coleman, Daniel Johnson, June Nawakii"
                        },
                        new
                        {
                            SongId = 78,
                            AlbumId = 6,
                            Length = 0.55000000000000004,
                            Name = "2 Lit 2 Late",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Hazzard, Gramma, Adam King Feeney"
                        },
                        new
                        {
                            SongId = 79,
                            AlbumId = 6,
                            Length = 4.0599999999999996,
                            Name = "Come See About Me",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Hazzard, Christopher Braide, Henry Walter"
                        },
                        new
                        {
                            SongId = 80,
                            AlbumId = 6,
                            Length = 3.4399999999999999,
                            Name = "Sir",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Nayvadius Wilburn, Wayne, Xavier Dotson"
                        },
                        new
                        {
                            SongId = 81,
                            AlbumId = 6,
                            Length = 3.1000000000000001,
                            Name = "Miami",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Shane Lindstrom, Diaz, Douglas Patterson"
                        },
                        new
                        {
                            SongId = 82,
                            AlbumId = 6,
                            Length = 3.4399999999999999,
                            Name = "Coco Chanel",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Joshua Adams, Inga Marchand, Ashley Bannister, Dillon Hart Francis, Sonny Moore"
                        },
                        new
                        {
                            SongId = 83,
                            AlbumId = 6,
                            Length = 0.57999999999999996,
                            Name = "Inspirations Outro",
                            Singer = "Nicki Minaj",
                            Writer = "Maraj, Adams, Bannister, Dillon, Moore"
                        },
                        new
                        {
                            SongId = 84,
                            AlbumId = 7,
                            Length = 3.04,
                            Name = "Future Nostalgia",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Jeff Bhasker, Clarence Coffee Jr"
                        },
                        new
                        {
                            SongId = 85,
                            AlbumId = 7,
                            Length = 3.0299999999999998,
                            Name = "Don't Start Now",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Caroline Ailin, Emily Warren, Ian Kirkpatrick"
                        },
                        new
                        {
                            SongId = 86,
                            AlbumId = 7,
                            Length = 3.29,
                            Name = "Cool",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Camille Purcell, Tove Lo, Shakka Philip, Benjamin Kohn, Thomas Barnes, Peter Kelleher"
                        },
                        new
                        {
                            SongId = 87,
                            AlbumId = 7,
                            Length = 3.1299999999999999,
                            Name = "Physical",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Jason Evigan, Clarence Coffee, JrSarah Hudson"
                        },
                        new
                        {
                            SongId = 88,
                            AlbumId = 7,
                            Length = 3.23,
                            Name = "Levitating",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Clarence Coffee, JrSarah Hudson,Stephen Kozmeniuk"
                        },
                        new
                        {
                            SongId = 89,
                            AlbumId = 7,
                            Length = 3.1400000000000001,
                            Name = "Pretty Please",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Julia Michaels, Caroline Ailin, Ian Kirkpatrick"
                        },
                        new
                        {
                            SongId = 90,
                            AlbumId = 7,
                            Length = 3.2799999999999998,
                            Name = "Hallucinate",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Samuel Lewis, Sophie Cooke"
                        },
                        new
                        {
                            SongId = 91,
                            AlbumId = 7,
                            Length = 3.1800000000000002,
                            Name = "Love Again",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Clarence Coffee, JrStephen Kozmeniuk, Chelcee Grimes, Bing Crosby, Max Wartell, Irving Wallman"
                        },
                        new
                        {
                            SongId = 92,
                            AlbumId = 7,
                            Length = 3.4100000000000001,
                            Name = "Break My Heart",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Andrew Wotman, Ali Tamposi, Stefan Johnson, Jordan Johnson, Andrew Farriss, Michael Hutchence"
                        },
                        new
                        {
                            SongId = 93,
                            AlbumId = 7,
                            Length = 3.3799999999999999,
                            Name = "Good in Bed",
                            Singer = "Dua Lipa",
                            Writer = "Dua Lipa, Michael Schulz, Melanie Fontana, Taylor Upsahl, David Biral, Denzel Baptiste"
                        },
                        new
                        {
                            SongId = 94,
                            AlbumId = 7,
                            Length = 2.46,
                            Name = "Boys Will Be Boys",
                            Singer = "Dua Lipa",
                            Writer = "Dua LipaKennediJustin TranterJason Evigan"
                        },
                        new
                        {
                            SongId = 95,
                            AlbumId = 8,
                            Length = 9.5800000000000001,
                            Name = "Magik Journey",
                            Singer = "Tiesto",
                            Writer = "Tiësto, Geert Huinink"
                        },
                        new
                        {
                            SongId = 96,
                            AlbumId = 8,
                            Length = 5.0099999999999998,
                            Name = "Close to You",
                            Singer = "Tiesto",
                            Writer = "Tiësto, Sarah Bettens"
                        },
                        new
                        {
                            SongId = 97,
                            AlbumId = 8,
                            Length = 6.4299999999999997,
                            Name = "Dallas 4 PM",
                            Singer = "Tiesto",
                            Writer = "Tiësto"
                        },
                        new
                        {
                            SongId = 98,
                            AlbumId = 8,
                            Length = 6.0700000000000003,
                            Name = "In My Memory",
                            Singer = "Tiesto",
                            Writer = "Tiësto, Nicola Hitchcock"
                        },
                        new
                        {
                            SongId = 99,
                            AlbumId = 8,
                            Length = 9.0700000000000003,
                            Name = "Obsession",
                            Singer = "Tiesto",
                            Writer = "Tiësto, Tom Holkenborg"
                        },
                        new
                        {
                            SongId = 100,
                            AlbumId = 8,
                            Length = 5.1299999999999999,
                            Name = "Battleship Grey",
                            Singer = "Tiesto",
                            Writer = "Tiësto, Kirsty Hawkshaw"
                        },
                        new
                        {
                            SongId = 101,
                            AlbumId = 8,
                            Length = 9.0099999999999998,
                            Name = "Flight 643",
                            Singer = "Tiesto",
                            Writer = "Tiësto"
                        },
                        new
                        {
                            SongId = 102,
                            AlbumId = 8,
                            Length = 6.46,
                            Name = "Lethal Industry",
                            Singer = "Tiesto",
                            Writer = "Tiësto"
                        },
                        new
                        {
                            SongId = 103,
                            AlbumId = 8,
                            Length = 8.2599999999999998,
                            Name = "Suburban Train",
                            Singer = "Tiesto",
                            Writer = "Tiësto, Ronald van Gelderen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
